spring:
    cloud:
        gateway:
            routes:
            - id: test_route
              uri: https://www.baidu.com
              predicates:
                - Query=url,baidu

            - id: qq_route
              uri: https://www.qq.com
              predicates:
                - Query=url,qq

            - id: product_route
              uri: lb://fancymall-product
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}

            - id: admin_route
              ## 从nacos loadbalance 到 renren-fast服务路径
              uri: lb://renren-fast
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

